language: generic
sudo: required
addons:
  apt:
    update: true
services:
  - docker

jobs:
  include:
  - stage: test
    env: Type='mock build test'
    before_install:
    - docker pull centos:centos7
    script:
    - ./include/travis/run_in_centos7_docker.sh include/travis/mock_build_test.sh
  - stage: cd
    git:
      depth: 999999
    env: Type='Continuous Deployment'
    script:
      - include/travis/copr-deploy.sh prepare
      - ./travis_wait "./include/travis/run_in_centos7_docker.sh include/travis/copr-deploy.sh build_srpm"
  - stage: deploy-copr
    env: Type='Copr deploy'
    before_deploy:
    - docker pull centos:centos7
    - openssl aes-256-cbc -K $encrypted_253525cedcf6_key -iv $encrypted_253525cedcf6_iv -in include/copr-mfl.enc -out include/copr-mfl -d
    - curl -O https://raw.githubusercontent.com/m3t/travis_wait/master/travis_wait
    - chmod 755 travis_wait
    deploy:
      skip_cleanup: true
      provider: script
      script: ./travis_wait "./include/travis/run_in_centos7_docker.sh include/travis/copr-deploy.sh"
      on:
        all_branches: true
stages:
  - test
  - name: cd
    if: branch = master AND type = push AND fork = false
  - name: deploy-copr
    if: branch =~ ^v\d+\.\d+\.\d+-.+$