NAME            := lustre-ldiskfs-zfs
PACKAGE_VERSION := 1
DIST_VERSION    := $(PACKAGE_VERSION)
PACKAGE_RELEASE := 4

include ./include/rpm.mk

$(NAME)-$(PACKAGE_VERSION)-$(PACKAGE_RELEASE).tgz: zfs-import-none.service
	mkdir $(NAME)-$(PACKAGE_VERSION)-$(PACKAGE_RELEASE)/
	cp $< $(NAME)-$(PACKAGE_VERSION)-$(PACKAGE_RELEASE)/
	tar czvf $@ $(NAME)-$(PACKAGE_VERSION)-$(PACKAGE_RELEASE)/
	rm -rf $(NAME)-$(PACKAGE_VERSION)-$(PACKAGE_RELEASE)/

dist: $(NAME)-$(PACKAGE_VERSION)-$(PACKAGE_RELEASE).tgz